# Generated by Django 5.1.3 on 2024-11-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_survey_created_at_alter_option_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('choice', 'Choice'), ('file', 'File Upload')], max_length=50),
        ),
    ]
