# Generated by Django 5.1.3 on 2024-11-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedetail',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='survey.response'),
        ),
    ]
