# Generated by Django 5.1.3 on 2024-11-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_response_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='certificate',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='survey.response'),
        ),
    ]
